version: "3.9"

services:
  mysql:
    ports:
      - "3308:3306"

  backend-python:
    ports:
      - "8002:8000"

  backend-go:
    ports:
      - "8082:8080"

  frontend:
    ports:
      - "5175:5173"

  nginx:
    ports:
      - "8090:80"
