version: "3.9"

services:
  mysql:
    ports:
      - "3307:3306"

  backend-python:
    ports:
      - "8001:8000"

  backend-go:
    ports:
      - "8081:8080"

  frontend:
    ports:
      - "5174:5173"

  nginx:
    ports:
      - "8092:80"
